"""Constants for the Keurig Connect integration."""

DOMAIN = "keurig"
MANUFACTURER = "Keurig"

SERVICE_BREW_HOT_WATER = "brew_hot_water"
SERVICE_BREW_HOT = "brew_hot"
SERVICE_BREW_ICED = "brew_iced"
SERVICE_BREW_RECOMMENDATION = "brew_recommendation"
SERVICE_BREW_FAVORITE = "brew_favorite"
SERVICE_CANCEL_BREW = "cancel_brew"
SERVICE_ADD_FAVORITE = "add_favorite"
SERVICE_UPDATE_FAVORITE = "update_favorite"
SERVICE_DELETE_FAVORITE = "delete_favorite"

ATTR_SIZE = "size"
ATTR_INTENSITY = "intensity"
ATTR_POD_BRAND = "pod_brand"
ATTR_POD_VARIETY = "pod_variety"
ATTR_POD_ROAST_TYPE = "pod_roast_type"
ATTR_POD_IS_TEA = "pod_is_tea"
ATTR_POD_IS_ICED = "pod_is_iced"
ATTR_POD_IS_FLAVORED = "pod_is_flavored"
ATTR_POD_IS_POWDERED = "pod_is_powdered"